/**********************************/
/* Table Name: 관리자 답글 */
/**********************************/
CREATE TABLE ADMIN_REPLY(
		ADMINREPLYNO NUMBER(10) NOT NULL PRIMARY KEY,
		SERVICENO NUMBER(10) NOT NULL,
		ADMINNO NUMBER(10) NOT NULL,
		ADMINREPLYTITLE VARCHAR2(50) NOT NULL,
		ADMINREPLYCONTENT CLOB    NOT NULL,
		ADMINREPLYVISIBLE CHAR(1) NOT NULL,
		RDATE DATE NOT NULL,
		UDATE DATE,
        file1                                   VARCHAR(100)          NULL,
        file1saved                            VARCHAR(100)          NULL,
        thumb1                              VARCHAR(100)          NULL,
        size1                                 NUMBER(10)      DEFAULT 0 NULL,
  FOREIGN KEY (SERVICENO) REFERENCES CUSTOMER_POST (SERVICENO),
  FOREIGN KEY (ADMINNO) REFERENCES ADMIN (ADMINNO)
);

COMMENT ON TABLE ADMIN_REPLY is '관리자 답글';
COMMENT ON COLUMN ADMIN_REPLY.ADMINREPLYNO is '관리자 답글 번호';
COMMENT ON COLUMN ADMIN_REPLY.SERVICENO is '고객센터 글 번호';
COMMENT ON COLUMN ADMIN_REPLY.ADMINNO is '관리자 번호';
COMMENT ON COLUMN ADMIN_REPLY.ADMINREPLYTITLE is '관리자 답글 제목';
COMMENT ON COLUMN ADMIN_REPLY.ADMINREPLYCONTENT is '관리자 답글 내용';
COMMENT ON COLUMN ADMIN_REPLY.ADMINREPLYVISIBLE is '공개여부';
COMMENT ON COLUMN ADMIN_REPLY.RDATE is '등록일';
COMMENT ON COLUMN ADMIN_REPLY.UDATE is '수정일';
COMMENT ON COLUMN ADMIN_REPLY.file1 is '메인 이미지';
COMMENT ON COLUMN ADMIN_REPLY.file1saved is '실제 저장된 메인 이미지';
COMMENT ON COLUMN ADMIN_REPLY.thumb1 is '메인 이미지 preview';
COMMENT ON COLUMN ADMIN_REPLY.size1 is '메인 이미지 크기';

DROP SEQUENCE ADMIN_REPLY_seq;
CREATE SEQUENCE ADMIN_REPLY_seq
  START WITH 1              -- 시작 번호
  INCREMENT BY 1          -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                     -- 다시 1부터 생성되는 것을 방지
  
  
  
-- 관리자 답글
-- 등록: 1건 이상
DELETE FROM ADMIN_REPLY;
INSERT INTO ADMIN_REPLY (ADMINREPLYNO, SERVICENO, ADMINNO, ADMINREPLYTITLE, ADMINREPLYCONTENT, ADMINREPLYVISIBLE, RDATE, FILE1, FILE1SAVED, THUMB1, SIZE1) 
VALUES (ADMINREPLYNO_seq.nextval, 1, 1, '관리자 답글의 제목입니다.', '관리자 답글을 등록합니다.', 'T', sysdate, '', '', '', '');

-- 전체 목록
--  기본적으로 질문글에 속해있는 데이터들이므로, 답글목록은 불필요할것이라고 여겨짐
SELECT ADMINREPLYNO, SERVICENO, ADMINNO, ADMINREPLYTITLE, ADMINREPLYCONTENT, ADMINREPLYVISIBLE, RDATE, FILE1, FILE1SAVED, THUMB1, SIZE1
FROM ADMIN_REPLY;

-- 조회
SELECT ADMINREPLYNO, SERVICENO, ADMINNO, ADMINREPLYTITLE, ADMINREPLYCONTENT, ADMINREPLYVISIBLE, RDATE, FILE1, FILE1SAVED, THUMB1, SIZE1
FROM ADMIN_REPLY
WHERE ADMINREPLYNO = 1;


-- 글 수정
UPDATE ADMIN_REPLY
SET ADMINREPLYTITLE = 'hello', ADMINREPLYCONTENT='and again', ADMINREPLYVISIBLE='N', UDATE=sysdate,
    file1='', file1saved='', thumb1='', size1=''
WHERE ADMINREPLYNO = 1;

-- 파일 수정

-- 삭제
DELETE FROM ADMIN_REPLY
WHERE ADMINREPLYNO = 1;

-- 레코드 갯수

-- *************** FK 자식 테이블일 경우 구현 시작 ***************
-- FK 컬럼 기준 카운트, 특정 그룹에 속한 레코드 갯수 산출
-- 1번 문의글에 등록된 답글 갯수는?
SELECT COUNT(*)
FROM ADMIN_REPLY
WHERE SERVICENO = 1;

-- FK 컬럼 기준 삭제, 특정 그룹에 속한 레코드 모두 삭제
-- 1번 문의글에 등록된 답글 삭제
DELETE FROM ADMIN_REPLY
WHERE SERVICENO = 1;

-- 부모 테이블과의 JOIN
SELECT s.SERVICENO, s.SERVICECATENO, s.MEMBERNO, s.SERVICETITLE, s.SERVICECONTENTS, s.SERVICEPASSWD, s.SERVICEVISIBLE, s.RDATE, s.UDATE,
    a.ADMINREPLYNO, a.SERVICENO, a.ADMINNO, a.ADMINREPLYTITLE, a.ADMINREPLYCONTENT, a.ADMINREPLYVISIBLE, a.RDATE
FROM CUSTOMER_POST s, ADMIN_REPLY a
WHERE s.SERVICENO = a.SERVICENO;



-- *************** FK 자식 테이블일 경우 구현 종료 ***************

-- 검색 목록(구현 권장)

-- 검색 + 페이징 목록(구현 권장)